apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zwtbyqynx-java-quarkus 
  janus-idp.io/tekton: zwtbyqynx-java-quarkus
  backstage.io/kubernetes-id: zwtbyqynx-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zwtbyqynx-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  